on : push
jobs : 
      first-job:
          runs-on : ubuntu-latest
          steps :
                - uses : actions/checkout@v3
                - run : npx eslint index.js
                - run : npm run test
                - run : node index.js