on : push
jobs : 
      first-job:
          runs-on : ubuntu-latest
          steps :
                - uses : actions/checkout@v3
                - run : npm eslint index.js
                - run : node index.js